name: 📚 Documentation or README.md issue report
description: Report an issue in the project's documentation or README.md file.
title: "[Docs]: "
labels: ["💾 Type: Docs"]
assignees:
  - malezjaa
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: What happened?
      description: Describe the issue here.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: |
        What steps can we follow to reproduce the issue?
      placeholder: |
        1. `npm install`
        2. `npm start:dev`
        3. See error...
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happened (or code)"
